// Main script

// Go talk to the player
// IF
// See([PC])
// NumTimesTalkedTo(0)
// !Global("OlrunJoined","LOCALS",1)
// THEN
// RESPONSE #100
// Dialogue(Nearest([PC]))
// END

IF
See([PC])
!Global("uxolrunPrelude","GLOBALS",1)
THEN
RESPONSE #100
Dialogue(Nearest([PC]))
SetGlobal("uxolrunPrelude","GLOBALS",1)
END

IF
See([PC])
Global("uxanariPrelude", "GLOBALS", 1)
!Global("uxPreludeDone","GLOBALS",1)
THEN
RESPONSE #100
EscapeAreaMove()
SetGlobal("uxPreludeDone","GLOBALS",1)
END
