// IF
// See([PC])
// NumTimesTalkedTo(0)
// !Global("AnariJoined","LOCALS",1)
// THEN
// RESPONSE #100
// Dialogue(Nearest([PC]))
// END

IF
See([PC])
Global("uxzarielPrelude", "GLOBALS", 1)
!Global("uxvoicePrelude","GLOBALS",1)
THEN
RESPONSE #100
Dialogue(Nearest([PC]))
SetGlobal("uxvoicePrelude","GLOBALS",1)
END

IF
See([PC])
Global("uxanariPrelude", "GLOBALS", 1)
!Global("uxPreludeDone","GLOBALS",1)
THEN
RESPONSE #100
EscapeAreaMove()
SetGlobal("uxPreludeDone","GLOBALS",1)
END
