// IF
// See([PC])
// NumTimesTalkedTo(0)
// !Global("ZarielJoined","LOCALS",1)
// THEN
// RESPONSE #100
// Dialogue(Nearest([PC]))
// END

IF
See([PC])
Global("uxatharPrelude", "GLOBALS", 1)
!Global("uxzarielPrelude","GLOBALS",1)
THEN
RESPONSE #100
Dialogue(Nearest([PC]))
SetGlobal("uxzarielPrelude","GLOBALS",1)
END

IF
See([PC])
Global("uxanariPrelude", "GLOBALS", 1)
!Global("uxPreludeDone","GLOBALS",1)
THEN
RESPONSE #100
EscapeAreaMove()
SetGlobal("uxPreludeDone","GLOBALS",1)
END
